// GENERATED FILE — DO NOT EDIT.
// Backend copy of src/utils/teamBalanceCore.ts, produced by
// functions/scripts/genTeamBalanceCore.mjs. Edit the client source and re-run
// the generator; tests/logic/balanceParity.test.ts fails if the two drift.
// Team-balance core — the ONE implementation of how a roster is split.
//
// This file is deliberately dependency-free (no imports, no RN, no Firebase,
// no `@/types`) for one reason: `functions/src/teamBalanceCore.ts` is a
// GENERATED byte-copy of it, so the phone and the scheduled Cloud Function
// cannot drift. Run `node scripts/genTeamBalanceCore.mjs` after every change;
// `tests/logic/balanceParity.test.ts` fails if the two ever diverge.
//
// The model in one sentence: make the teams fair enough on rating, and inside
// the fair options mix people up as much as possible relative to the last few
// game-nights.
//
// Balance is the CONSTRAINT, variety is the GOAL inside it. Perfect balance is
// explicitly not the objective — a split that is 0.05 worse on rating but
// breaks up four pairs that played together last week is the better split.

// ─── Rating ───────────────────────────────────────────────────────────────

/** Neutral score for an unrated player — the middle of the 1.0–5.0 scale. */
export const NEUTRAL_RATING = 3;

/**
 * Coerce any stored rating onto the live 0–5 scale. Values created before the
 * 1–10 → 1–5 migration still sit in `adminRatings` / guest `estimatedRating`
 * as 6–10; read raw, an old "8" towers over a neutral 3 and skews every split.
 * Anything above the max is treated as the old scale and halved. Idempotent.
 */
export function normalizeRating(v: number): number {
  const r = v > 5 ? v / 2 : v;
  // Floor at 0 (not 1): the live scale is 0–5 and sub-1 ratings are real.
  return Math.min(5, Math.max(0, r));
}

// ─── Tunables ─────────────────────────────────────────────────────────────
// Every number the model can be argued about lives here, named, in one block.

/** Rating gap (strongest team average − weakest) at or below which the split
 *  is excellent: inside this band, variety decides and chasing another
 *  hundredth of balance is pointless. */
export const GAP_EXCELLENT = 0.1;
/** Still a good split; a small balance penalty applies. */
export const GAP_GOOD = 0.15;
/** The hard ceiling in normal operation — beyond this a split is not offered. */
export const GAP_MAX = 0.2;
/** When even the best possible split for this roster exceeds GAP_MAX, the
 *  window becomes [minGap, minGap + this]. */
export const FALLBACK_MARGIN = 0.03;

/** Weight of a shared past game-night, by how recent the pair's MEETING was
 *  (not by calendar date — see buildPairRepeatWeights). */
export const REPEAT_WEIGHTS = [1.0, 0.6, 0.3];
/** How many shared meetings back the memory reaches. */
export const HISTORY_MEETINGS = REPEAT_WEIGHTS.length;
/**
 * How many recent game-nights to load. The window is per PAIR (the last
 * HISTORY_MEETINGS nights BOTH of them played), so this only has to be deep
 * enough to contain them: for a weekly club, 8 nights covers 3 meetings even
 * for someone who shows up two weeks in three.
 */
export const HISTORY_GAMES = 8;

/** How many independent splits to generate before choosing one. */
export const CANDIDATES = 64;
/** Cap on refinement passes — the loop exits on its own long before this. */
const MAX_REFINE_PASSES = 60;
/** Sideways swaps applied to the chosen split, for variety at equal quality. */
const WANDER_STEPS = 10;
/**
 * How much rating gap the sideways walk may add to the split it was handed.
 * It must be a slack, never the distance to the ceiling: given the whole
 * acceptable region to roam, and nothing to gain by staying put (a club with no
 * history has the same repeat score everywhere), the walk slid straight to the
 * 0.20 edge and made every split as unbalanced as the rules allow.
 */
const WANDER_GAP_SLACK = 0.03;
/** Weight of one stack-penalty point inside the refinement cost. */
const STACK_WEIGHT = 0.02;
/** Strategy A: repeat points that equal one unit of cost, as a fraction of the
 *  pair count. 0.2 of 30 pairs = 6 — i.e. one cost unit ≈ six pairs that were
 *  together last week. Absolute on purpose: normalising against the candidate
 *  pool would make the same split score differently from run to run. */
const REPEAT_SCALE_PER_PAIR = 0.2;
/** Strategy A: splits within this much of the best cost are treated as equally
 *  good, and one is picked at random. */
const COST_EPSILON = 0.05;
/**
 * How many DISTINCT near-best splits to keep as finalists, and how much worse
 * than the best a finalist may be.
 *
 * Both halves are needed. Once history guides the search, the objective has an
 * essentially unique optimum and every candidate descends into it: measured on
 * the real roster, 200 presses produced one composition, with 55 of the 105
 * possible pairings never occurring once. "Regenerate" has to be able to answer
 * differently, so the pick is made from a handful of distinct splits — bounded,
 * so second-best never means noticeably worse. 0.25 ≈ one and a half repeated
 * pairs, or a step from an excellent gap to the middle of the good band.
 *
 * 16 is measured, not guessed (scripts/simulateTeamBalance.mjs): at 5 finalists
 * the button returned only 5 distinct splits in 40 presses, at 16 it returns
 * ~16–23, and the quality metrics do not get worse — with the trade bounded,
 * more finalists actually break up recurring cliques slightly better.
 */
const FINALISTS = 16;
const SELECT_MAX_TRADE = 0.25;
/**
 * Per-candidate jitter applied to the pair weights DURING the search only —
 * never when scoring the result. Each candidate is nudged to care a little more
 * about breaking up some pairs than others, so the restarts land on genuinely
 * different near-optimal splits instead of all funnelling into one.
 */
const SEARCH_JITTER = 0.35;
/** Strategy B: repeat scores are bucketed this coarsely before ranking, so
 *  noise below one weak meeting doesn't decide the split. */
const REPEAT_BUCKET = 0.5;
/** Strategy B: inside the winning repeat bucket, gaps within this of the best
 *  are treated as equal and picked between at random. */
const GAP_EPSILON = 0.03;

/** Guest roster ids are minted per game, so a guest has no identity across
 *  game-nights and can carry no pair history. */
const GUEST_PREFIX = 'guest:';

// ─── Types ────────────────────────────────────────────────────────────────

export interface ScoredPlayer {
  id: string;
  rating: number;
}

export interface BuildTeam {
  ids: string[];
  total: number;
  /** Fixed target size — balancing AVERAGES needs the final head count. */
  size: number;
}

/** One past game-night's split, newest first is NOT assumed — sorted here. */
export interface PastSplit {
  /** ms epoch of the game-night, used only for ordering. */
  startsAt: number;
  /** The teams as first drawn (`originalTeams ?? teams`). */
  teams: string[][];
}

export type BalanceStrategy = 'A' | 'B';

/**
 * Which tolerance band a split's rating gap fell into. Recorded on every split
 * so the parameters can eventually be calibrated from real weeks instead of
 * from a simulation: 'A' ≤ 0.10 excellent, 'B' ≤ 0.15 good, 'C' ≤ 0.20
 * tolerable, 'over' only reachable through the fallback.
 */
export type BalanceBand = 'A' | 'B' | 'C' | 'over';

export function balanceBand(gap: number): BalanceBand {
  if (gap <= GAP_EXCELLENT + 1e-9) return 'A';
  if (gap <= GAP_GOOD + 1e-9) return 'B';
  if (gap <= GAP_MAX + 1e-9) return 'C';
  return 'over';
}

export interface CoreInput {
  playerIds: string[];
  /** Roster id → raw rating. Missing/≤0 = unrated → NEUTRAL_RATING. */
  ratings: Record<string, number>;
  numTeams: number;
  /** Capacity per team; players beyond numTeams × perTeam are benched. */
  perTeam: number;
  /** Pair key → repeat weight, from buildPairRepeatWeights. Absent = no
   *  history, and the split is decided on balance alone. */
  pairWeights?: Record<string, number>;
  strategy?: BalanceStrategy;
  candidates?: number;
  /** Injectable for deterministic tests and for client/server parity. */
  rng?: () => number;
}

export interface CoreResult {
  /** Team rosters, ordered by team index. */
  teams: string[][];
  /** Players who did not fit under the capacity, weakest last. */
  bench: string[];
  /** Strongest team average − weakest. */
  gap: number;
  /** Total repeat weight carried by this split. */
  repeat: number;
  /** Extreme-stacking penalty (see stackPenalty). */
  stack: number;
  /** Which tolerance band `gap` fell into — recorded for later calibration. */
  band: BalanceBand;
  /** True when no candidate reached GAP_MAX and the fallback window was used. */
  fallback: boolean;
  /** How many roster ids had no rating. */
  unratedCount: number;
}

// ─── Pair history ─────────────────────────────────────────────────────────

/** Order-independent key for a pair of roster ids. */
export function pairKey(a: string, b: string): string {
  return a < b ? `${a}|${b}` : `${b}|${a}`;
}

/**
 * Turn recent game-nights into a pair → repeat-weight map.
 *
 * The window is per PAIR, not per calendar: for each pair we walk back through
 * the splits and count only the nights where BOTH players appear, up to
 * HISTORY_MEETINGS of them. A night one of them missed does not consume a slot
 * — otherwise a player who skips two weeks would look "fresh" to everyone.
 *
 * A night contributes weight only if they were on the SAME team in it; a night
 * they spent on opposite teams still consumes a slot (they met, and that meeting
 * is evidence of nothing repeating). Splits with no usable teams must be
 * filtered out by the caller — a night we know nothing about must not consume a
 * slot either.
 *
 * Guests are skipped entirely: their ids are per-game and mean nothing here.
 */
export function buildPairRepeatWeights(
  splits: PastSplit[],
): Record<string, number> {
  const ordered = splits
    .filter((s) => s.teams.some((t) => t.length > 0))
    .slice()
    .sort((a, b) => b.startsAt - a.startsAt);

  const weights: Record<string, number> = {};
  const meetings: Record<string, number> = {};

  for (const split of ordered) {
    // roster id → team index, for real (non-guest) players only.
    const teamOf: Record<string, number> = {};
    const members: string[] = [];
    split.teams.forEach((team, idx) => {
      for (const id of team) {
        if (!id || id.startsWith(GUEST_PREFIX)) continue;
        if (teamOf[id] !== undefined) continue; // defensive: id in two teams
        teamOf[id] = idx;
        members.push(id);
      }
    });
    for (let i = 0; i < members.length; i++) {
      for (let j = i + 1; j < members.length; j++) {
        const key = pairKey(members[i], members[j]);
        const seen = meetings[key] ?? 0;
        if (seen >= HISTORY_MEETINGS) continue;
        meetings[key] = seen + 1;
        if (teamOf[members[i]] === teamOf[members[j]]) {
          weights[key] = (weights[key] ?? 0) + REPEAT_WEIGHTS[seen];
        }
      }
    }
  }
  return weights;
}

/** Total repeat weight carried by a split: every within-team pair, summed. */
export function repeatPenalty(
  teams: BuildTeam[],
  pairWeights: Record<string, number> | undefined,
): number {
  if (!pairWeights) return 0;
  let total = 0;
  for (const t of teams) {
    for (let i = 0; i < t.ids.length; i++) {
      for (let j = i + 1; j < t.ids.length; j++) {
        total += pairWeights[pairKey(t.ids[i], t.ids[j])] ?? 0;
      }
    }
  }
  return total;
}

/**
 * A copy of the pair weights with each entry scaled by an independent random
 * factor in [1 − SEARCH_JITTER, 1 + SEARCH_JITTER]. Used to steer one restart
 * of the search; results are always scored on the true weights.
 */
function jitterWeights(
  weights: Record<string, number>,
  rng: () => number,
): Record<string, number> {
  const out: Record<string, number> = {};
  for (const key in weights) {
    out[key] = weights[key] * (1 + (rng() * 2 - 1) * SEARCH_JITTER);
  }
  return out;
}

/** Repeat weight a single player carries against one team's current members. */
function repeatOfPlayerIn(
  id: string,
  team: BuildTeam,
  pairWeights: Record<string, number> | undefined,
): number {
  if (!pairWeights) return 0;
  let total = 0;
  for (const other of team.ids) {
    if (other === id) continue;
    total += pairWeights[pairKey(id, other)] ?? 0;
  }
  return total;
}

// ─── Balance primitives ───────────────────────────────────────────────────

/** In-place Fisher–Yates shuffle using the caller's RNG. */
function shuffleInPlace<T>(arr: T[], rng: () => number): void {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    const tmp = arr[i];
    arr[i] = arr[j];
    arr[j] = tmp;
  }
}

/**
 * Team sizes, as even as possible, capped at `capacity` each. The remainder
 * goes to a RANDOM subset of teams, so "team א is always the bigger one" never
 * becomes a fixed pattern.
 */
export function splitSizes(
  count: number,
  numTeams: number,
  capacity: number,
  rng: () => number,
): number[] {
  const placed = Math.min(count, numTeams * capacity);
  const base = Math.floor(placed / numTeams);
  const extra = placed % numTeams;
  const order: number[] = [];
  for (let i = 0; i < numTeams; i++) order.push(i);
  shuffleInPlace(order, rng);
  const sizes: number[] = [];
  for (let i = 0; i < numTeams; i++) sizes.push(base);
  for (let i = 0; i < extra; i++) sizes[order[i]] += 1;
  return sizes;
}

export function averageOf(t: BuildTeam): number {
  return t.ids.length > 0 ? t.total / t.ids.length : NEUTRAL_RATING;
}

/** Strongest team average minus weakest. Zero = perfectly balanced. */
export function spreadOf(teams: BuildTeam[]): number {
  let min = Infinity;
  let max = -Infinity;
  for (const t of teams) {
    const a = averageOf(t);
    if (a < min) min = a;
    if (a > max) max = a;
  }
  return max - min;
}

/**
 * The strongest and weakest ends of the roster, TIE-INCLUSIVE: everyone at or
 * above the Nth-highest rating, and everyone at or below the Nth-lowest. Taking
 * literally N ids would let a tie at the cut-off hide a pile-up.
 */
export function extremeSets(
  scored: ScoredPlayer[],
  numTeams: number,
): { top: Record<string, true>; bottom: Record<string, true> } {
  const sorted = scored.map((p) => p.rating).sort((a, b) => b - a);
  const topCut = sorted[Math.min(numTeams, sorted.length) - 1];
  const bottomCut = sorted[Math.max(0, sorted.length - numTeams)];
  const top: Record<string, true> = {};
  const bottom: Record<string, true> = {};
  for (const p of scored) {
    if (p.rating >= topCut) top[p.id] = true;
    else if (p.rating <= bottomCut) bottom[p.id] = true;
  }
  return { top, bottom };
}

/**
 * How badly a split stacks the extremes: the sum of SQUARED per-team counts of
 * the top (and bottom) players, smallest when they are spread one per team.
 * Squared and not `max(0, n − 1)`, which scores 3/1/1 and 2/2/1 identically.
 */
export function stackPenalty(
  teams: BuildTeam[],
  top: Record<string, true>,
  bottom: Record<string, true>,
): number {
  let penalty = 0;
  for (const t of teams) {
    let nTop = 0;
    let nBottom = 0;
    for (const id of t.ids) {
      if (top[id]) nTop += 1;
      else if (bottom[id]) nBottom += 1;
    }
    penalty += nTop * nTop + nBottom * nBottom;
  }
  return penalty;
}

/**
 * The balance term, in cost units. Continuous and progressively steeper, so
 * there is no cliff at a zone edge: 0.099 and 0.101 cost almost the same, while
 * 0.19 costs a great deal more than 0.09.
 *
 *   0.00–0.10 (excellent) → 0.00–0.15   slope  1.5 / rating point
 *   0.10–0.15 (good)      → 0.15–0.50   slope  7.0
 *   0.15–0.20 (tolerable) → 0.50–1.20   slope 14.0
 *   above the ceiling     → steep, finite, so a descent can climb back down
 */
export function balancePenalty(gap: number): number {
  if (gap <= GAP_EXCELLENT) return 0.15 * (gap / GAP_EXCELLENT);
  if (gap <= GAP_GOOD) {
    return 0.15 + 0.35 * ((gap - GAP_EXCELLENT) / (GAP_GOOD - GAP_EXCELLENT));
  }
  if (gap <= GAP_MAX) {
    return 0.5 + 0.7 * ((gap - GAP_GOOD) / (GAP_MAX - GAP_GOOD));
  }
  return 1.2 + 6 * (gap - GAP_MAX);
}

/** Repeat points worth one unit of cost, for a split of this shape. */
export function repeatScale(teams: BuildTeam[]): number {
  let pairs = 0;
  for (const t of teams) pairs += (t.ids.length * (t.ids.length - 1)) / 2;
  return Math.max(1, REPEAT_SCALE_PER_PAIR * pairs);
}

// ─── Search ───────────────────────────────────────────────────────────────

/**
 * One greedy pass: strongest player first, into whichever team is furthest
 * below its share. `total / size` (not `total`) is the yardstick — that is what
 * balances averages rather than sums, so a team carrying an extra player is
 * allowed a bigger sum.
 *
 * With pair history present, ties between equally-hungry teams are broken
 * toward the team the player shares the LEAST history with, which seeds the
 * search in a varied place instead of leaving it all to the refinement.
 */
export function greedyBuild(
  scored: ScoredPlayer[],
  sizes: number[],
  rng: () => number,
  pairWeights?: Record<string, number>,
): { teams: BuildTeam[]; bench: ScoredPlayer[] } {
  const teams: BuildTeam[] = sizes.map((size) => ({ ids: [], total: 0, size }));
  const players = scored.slice();
  shuffleInPlace(players, rng); // varies the order inside every tied-rating bucket
  players.sort((a, b) => b.rating - a.rating); // stable → the shuffle survives

  const bench: ScoredPlayer[] = [];
  for (const p of players) {
    const open = teams.filter((t) => t.ids.length < t.size);
    if (open.length === 0) {
      bench.push(p);
      continue;
    }
    open.sort((a, b) => {
      const da = a.total / Math.max(1, a.size);
      const db = b.total / Math.max(1, b.size);
      if (Math.abs(da - db) > 1e-9) return da - db;
      const ra = repeatOfPlayerIn(p.id, a, pairWeights);
      const rb = repeatOfPlayerIn(p.id, b, pairWeights);
      if (Math.abs(ra - rb) > 1e-9) return ra - rb;
      if (a.ids.length !== b.ids.length) return a.ids.length - b.ids.length;
      return rng() - 0.5;
    });
    open[0].ids.push(p.id);
    open[0].total += p.rating;
  }
  return { teams, bench };
}

/** Swap two players between teams, keeping the running totals in step. */
function applySwap(
  ti: BuildTeam,
  a: number,
  tj: BuildTeam,
  b: number,
  rating: (id: string) => number,
): void {
  const ida = ti.ids[a];
  const idb = tj.ids[b];
  ti.ids[a] = idb;
  tj.ids[b] = ida;
  ti.total += rating(idb) - rating(ida);
  tj.total += rating(ida) - rating(idb);
}

/**
 * Steepest-descent refinement against whatever `cost` the caller cares about.
 * Team sizes are preserved, so it can only improve the split. Among swaps that
 * improve by the same amount it picks at random — always taking the first in
 * scan order made every descent drain into the same handful of splits.
 */
export function refineSwaps(
  teams: BuildTeam[],
  rating: (id: string) => number,
  cost: (t: BuildTeam[]) => number,
  rng: () => number,
): void {
  for (let pass = 0; pass < MAX_REFINE_PASSES; pass++) {
    let bestGain = 0;
    let best: { i: number; j: number; a: number; b: number }[] = [];
    const current = cost(teams);
    for (let i = 0; i < teams.length; i++) {
      for (let j = i + 1; j < teams.length; j++) {
        const ti = teams[i];
        const tj = teams[j];
        for (let a = 0; a < ti.ids.length; a++) {
          for (let b = 0; b < tj.ids.length; b++) {
            // Try it for real and undo — the cost depends on WHO sits where
            // (stacking, pair history), not just on the totals.
            applySwap(ti, a, tj, b, rating);
            const gain = current - cost(teams);
            applySwap(ti, a, tj, b, rating);
            if (gain <= 1e-9) continue;
            if (gain > bestGain + 1e-9) {
              bestGain = gain;
              best = [{ i, j, a, b }];
            } else if (gain >= bestGain - 1e-9) {
              best.push({ i, j, a, b });
            }
          }
        }
      }
    }
    if (best.length === 0) return;
    const pick = best[Math.floor(rng() * best.length)];
    applySwap(teams[pick.i], pick.a, teams[pick.j], pick.b, rating);
  }
}

/**
 * Random walk through the splits that are as good as the one we picked.
 *
 * "As good" is one budget in one currency: a move is allowed while the total
 * cost (balance + repeats) stays within `budget` of where the walk STARTED,
 * the gap stays under `maxGap`, and stacking never worsens. The budget is
 * measured from the starting cost, not from the current one, so a long walk
 * can't creep away one epsilon at a time.
 *
 * Without this the split is deterministic. Once history guides both the greedy
 * seeding and the refinement, all 64 candidates converge on the same answer —
 * measured, before this existed: 200 presses produced pairs that appeared
 * 200/200 times and 55 of 105 possible pairings that never occurred at all.
 * Pressing "regenerate" has to be able to return something else.
 */
export function wander(
  teams: BuildTeam[],
  rating: (id: string) => number,
  top: Record<string, true>,
  bottom: Record<string, true>,
  pairWeights: Record<string, number> | undefined,
  maxGap: number,
  steps: number,
  budget: number,
  rng: () => number,
): void {
  const scale = repeatScale(teams);
  const costNow = () =>
    balancePenalty(spreadOf(teams)) + repeatPenalty(teams, pairWeights) / scale;
  const baseStack = stackPenalty(teams, top, bottom);
  const ceiling = costNow() + budget;

  for (let s = 0; s < steps; s++) {
    const moves: { i: number; j: number; a: number; b: number }[] = [];
    for (let i = 0; i < teams.length; i++) {
      for (let j = i + 1; j < teams.length; j++) {
        const ti = teams[i];
        const tj = teams[j];
        for (let a = 0; a < ti.ids.length; a++) {
          for (let b = 0; b < tj.ids.length; b++) {
            applySwap(ti, a, tj, b, rating);
            const ok =
              spreadOf(teams) <= maxGap + 1e-9 &&
              stackPenalty(teams, top, bottom) <= baseStack &&
              costNow() <= ceiling + 1e-9;
            applySwap(ti, a, tj, b, rating);
            if (ok) moves.push({ i, j, a, b });
          }
        }
      }
    }
    if (moves.length === 0) return;
    const m = moves[Math.floor(rng() * moves.length)];
    applySwap(teams[m.i], m.a, teams[m.j], m.b, rating);
  }
}

// ─── The split ────────────────────────────────────────────────────────────

interface Candidate {
  teams: BuildTeam[];
  bench: ScoredPlayer[];
  gap: number;
  repeat: number;
  stack: number;
}

/**
 * Build a split. Balance is the constraint (GAP_MAX, or a fallback window when
 * the roster makes it unreachable), pair history is the goal inside it, and a
 * random pick between near-equal options keeps reruns from repeating.
 */
export function balanceCore(input: CoreInput): CoreResult {
  const rng = input.rng ?? Math.random;
  const strategy: BalanceStrategy = input.strategy ?? 'A';
  const pairWeights = input.pairWeights;

  // Dedupe FIRST: a duplicate id would otherwise be placed on two teams.
  const seen: Record<string, true> = {};
  const playerIds: string[] = [];
  for (const id of input.playerIds) {
    if (!id || seen[id]) continue;
    seen[id] = true;
    playerIds.push(id);
  }
  const numTeams = Math.max(1, Math.min(input.numTeams, playerIds.length));

  let unratedCount = 0;
  const scored: ScoredPlayer[] = playerIds.map((id) => {
    const known = input.ratings[id];
    if (typeof known === 'number' && known > 0) {
      return { id, rating: normalizeRating(known) };
    }
    unratedCount += 1;
    return { id, rating: NEUTRAL_RATING };
  });
  const ratingOf = (id: string) => {
    const known = input.ratings[id];
    return typeof known === 'number' && known > 0
      ? normalizeRating(known)
      : NEUTRAL_RATING;
  };

  const { top, bottom } = extremeSets(scored, numTeams);
  const perTeam = Math.max(1, input.perTeam);
  const count = input.candidates ?? CANDIDATES;

  const pool: Candidate[] = [];
  for (let k = 0; k < count; k++) {
    // Each restart searches with slightly different priorities (see
    // SEARCH_JITTER) so the pool holds real alternatives, not 64 copies of one
    // answer. Scoring below always uses the true weights.
    const searchWeights = pairWeights
      ? jitterWeights(pairWeights, rng)
      : undefined;
    const built = greedyBuild(
      scored,
      splitSizes(scored.length, numTeams, perTeam, rng),
      rng,
      searchWeights,
    );
    const teams = built.teams;
    // Phase 1 — get into the fair region on rating + stacking alone. Chasing
    // variety before the split is balanced just wastes the descent.
    refineSwaps(
      teams,
      ratingOf,
      (t) => spreadOf(t) + STACK_WEIGHT * stackPenalty(t, top, bottom),
      rng,
    );
    // Phase 2 — trade INSIDE the fair region for variety. The two strategies
    // differ only in what they are willing to trade.
    if (searchWeights) {
      const scale = repeatScale(teams);
      refineSwaps(
        teams,
        ratingOf,
        strategy === 'A'
          ? (t) =>
              balancePenalty(spreadOf(t)) +
              repeatPenalty(t, searchWeights) / scale +
              STACK_WEIGHT * stackPenalty(t, top, bottom)
          : // B keeps balance as a pure constraint: minimise repeats, and pay a
            // large fixed price only for crossing the ceiling.
            (t) =>
              repeatPenalty(t, searchWeights) / scale +
              100 * Math.max(0, spreadOf(t) - GAP_MAX) +
              STACK_WEIGHT * stackPenalty(t, top, bottom),
        rng,
      );
    }
    pool.push({
      teams,
      bench: built.bench,
      gap: spreadOf(teams),
      repeat: repeatPenalty(teams, pairWeights),
      stack: stackPenalty(teams, top, bottom),
    });
  }

  // Balance constraint. Normally the ceiling; when no candidate can reach it,
  // the window opens just above the best gap this roster allows.
  const minGap = Math.min(...pool.map((c) => c.gap));
  const fallback = minGap > GAP_MAX;
  const gapLimit = fallback ? minGap + FALLBACK_MARGIN : GAP_MAX;
  let eligible = pool.filter((c) => c.gap <= gapLimit + 1e-9);
  if (eligible.length === 0) eligible = pool; // never fail to produce a split

  // Stacking stays a filter, not a currency: variety may not buy a pile-up of
  // the strongest players. Relaxed by one step only if it would leave too few
  // splits to choose between (which would cost the variety we came for).
  const minStack = Math.min(...eligible.map((c) => c.stack));
  let unstacked = eligible.filter((c) => c.stack === minStack);
  if (unstacked.length < 8) {
    unstacked = eligible.filter((c) => c.stack <= minStack + 2);
  }

  const chosen =
    strategy === 'A'
      ? pickStrategyA(unstacked, rng)
      : pickStrategyB(unstacked, rng);

  wander(
    chosen.teams,
    ratingOf,
    top,
    bottom,
    pairWeights,
    Math.min(gapLimit, chosen.gap + WANDER_GAP_SLACK),
    WANDER_STEPS,
    COST_EPSILON,
    rng,
  );

  const finalGap = spreadOf(chosen.teams);
  return {
    teams: chosen.teams.map((t) => t.ids.slice()),
    bench: chosen.bench.map((p) => p.id),
    gap: finalGap,
    band: balanceBand(finalGap),
    repeat: repeatPenalty(chosen.teams, pairWeights),
    stack: stackPenalty(chosen.teams, top, bottom),
    fallback,
    unratedCount,
  };
}

/**
 * Strategy A — one continuous score: a progressive balance penalty plus the
 * repeat weight on an ABSOLUTE scale (one cost unit ≈ six pairs that were
 * together last week). Nothing is normalised against the candidate pool, so a
 * given split always scores the same regardless of what it was generated
 * alongside. Splits within COST_EPSILON of the best are equally good.
 */
function pickStrategyA(pool: Candidate[], rng: () => number): Candidate {
  const scale = repeatScale(pool[0].teams);
  const cost = (c: Candidate) => balancePenalty(c.gap) + c.repeat / scale;
  const best = Math.min(...pool.map(cost));
  const finalists = distinct(pool)
    .filter((c) => cost(c) <= best + SELECT_MAX_TRADE)
    .sort((a, b) => cost(a) - cost(b))
    .slice(0, FINALISTS);
  return finalists[Math.floor(rng() * finalists.length)] ?? pool[0];
}

/** One entry per distinct composition — 64 copies of the same split are one
 *  choice, not 64. */
function distinct(pool: Candidate[]): Candidate[] {
  const seen: Record<string, true> = {};
  const out: Candidate[] = [];
  for (const c of pool) {
    const key = c.teams
      .map((t) => t.ids.slice().sort().join(','))
      .sort()
      .join('|');
    if (seen[key]) continue;
    seen[key] = true;
    out.push(c);
  }
  return out;
}

/**
 * Strategy B — balance purely as a constraint (already applied by the caller),
 * then fewest repeats wins, then the smaller gap breaks the tie. Repeats are
 * bucketed so that noise below one weak meeting doesn't decide the split.
 */
function pickStrategyB(pool: Candidate[], rng: () => number): Candidate {
  const unique = distinct(pool);
  const bucket = (c: Candidate) => Math.round(c.repeat / REPEAT_BUCKET);
  const bestBucket = Math.min(...unique.map(bucket));
  const inBucket = unique.filter((c) => bucket(c) === bestBucket);
  const bestGap = Math.min(...inBucket.map((c) => c.gap));
  const finalists = inBucket
    .filter((c) => c.gap <= bestGap + GAP_EPSILON)
    .slice(0, FINALISTS);
  return finalists[Math.floor(rng() * finalists.length)] ?? unique[0];
}
