// withScreenCapture — Expo config plugin that adds the native PixelCopy
// screen-capture module to the generated Android project on every prebuild.
//
// android/ is gitignored (regenerated by prebuild), so the canonical Kotlin
// sources live under plugins/screenshot-src/ (tracked in git); this plugin
// copies them in and registers the package in MainApplication.
//
// It:
//   1. copies plugins/screenshot-src/*.kt → android/app/.../screencapture/
//   2. registers ScreenCapturePackage in MainApplication's package list
//
// Both steps are idempotent. iOS is unaffected — the JS wrapper falls back to
// react-native-view-shot when the native module is absent (iOS / Expo Go).

const { withDangerousMod, withMainApplication } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const PKG_PATH = 'com/studiogameslime/soccerapp/screencapture';
const REGISTER = 'com.studiogameslime.soccerapp.screencapture.ScreenCapturePackage()';

function copyKotlin(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const androidRoot = cfg.modRequest.platformProjectRoot;
      const srcDir = path.join(__dirname, 'screenshot-src');
      const destDir = path.join(androidRoot, 'app/src/main/java', PKG_PATH);
      fs.mkdirSync(destDir, { recursive: true });
      for (const f of ['ScreenCaptureModule.kt', 'ScreenCapturePackage.kt']) {
        fs.copyFileSync(path.join(srcDir, f), path.join(destDir, f));
      }
      return cfg;
    },
  ]);
}

function registerPackage(config) {
  return withMainApplication(config, (cfg) => {
    if (!cfg.modResults.contents.includes('ScreenCapturePackage')) {
      cfg.modResults.contents = cfg.modResults.contents.replace(
        'val packages = PackageList(this).packages',
        `val packages = PackageList(this).packages\n            packages.add(${REGISTER})`,
      );
    }
    return cfg;
  });
}

module.exports = function withScreenCapture(config) {
  config = copyKotlin(config);
  config = registerPackage(config);
  return config;
};
