/**
 * withJoryioSdk — links the vendored Joryio native SDK into the Android build.
 *
 * The SDK is not published: @joryio/react-native-sdk 404s on npm and the pods
 * (Joryio, JoryioUI) are absent from CocoaPods, so the sources live in
 * vendor/joryio and are wired in from there.
 *
 * React Native autolinking picks up vendor/joryio/react-native-sdk through the
 * `file:` dependency in package.json, but that module declares
 *     implementation project(':joryio-sdk')
 *     implementation project(':joryio-sdk-ui')
 * and Gradle cannot resolve those unless the host app's settings.gradle
 * declares them. android/ is gitignored and regenerated by prebuild, so the
 * declaration has to be re-applied on every prebuild — hence this plugin
 * rather than a one-off edit.
 */
const { withSettingsGradle } = require('@expo/config-plugins');

const MARKER = "// joryio-sdk";

const BLOCK = `
${MARKER} — vendored native SDK (not on Maven; see vendor/joryio)
include ':joryio-sdk'
project(':joryio-sdk').projectDir = new File(rootProject.projectDir, '../vendor/joryio/android/joryio')
include ':joryio-sdk-ui'
project(':joryio-sdk-ui').projectDir = new File(rootProject.projectDir, '../vendor/joryio/android/joryio-ui')
`;

module.exports = function withJoryioSdk(config) {
  return withSettingsGradle(config, (cfg) => {
    if (cfg.modResults.contents.includes(MARKER)) return cfg;
    cfg.modResults.contents += BLOCK;
    return cfg;
  });
};
