/**
 * withJoryioSdk — links the vendored Joryio native SDK into the Android build.
 *
 * The SDK is not published: @joryio/react-native-sdk 404s on npm and the pods
 * (Joryio, JoryioUI) are absent from CocoaPods, so the sources live in
 * vendor/joryio and are wired in from there.
 *
 * React Native autolinking picks up vendor/joryio/react-native-sdk through the
 * `file:` dependency in package.json, but that module declares
 *     implementation project(':joryio-sdk')
 *     implementation project(':joryio-sdk-ui')
 * and Gradle cannot resolve those unless the host app's settings.gradle
 * declares them. android/ is gitignored and regenerated by prebuild, so the
 * declaration has to be re-applied on every prebuild — hence this plugin
 * rather than a one-off edit.
 */
const { withSettingsGradle, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const MARKER = "// joryio-sdk";
const POD_MARKER = "# joryio-sdk";

// The iOS half of the same problem. Autolinking adds `joryio-react-native`,
// whose podspec declares `s.dependency "Joryio/UI"` — and CocoaPods cannot
// resolve that name from anywhere, because the pod is not on trunk and the
// repo its podspec names does not exist. Declaring the path pod is what
// satisfies it.
//
// ios/ is gitignored and regenerated by prebuild exactly like android/, so a
// hand-edited Podfile survives locally and vanishes in a clean build — which is
// precisely how the first iOS build of this SDK failed:
//     [!] Unable to find a specification for `Joryio/UI` depended upon by
//         `joryio-react-native`
const POD_LINE = `
  ${POD_MARKER} — vendored native SDK (not on CocoaPods trunk; see vendor/joryio)
  pod 'Joryio', :path => '../vendor/joryio/ios', :subspecs => ['Core', 'UI']
`;

function withJoryioPod(config) {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      let contents = fs.readFileSync(podfile, 'utf8');
      if (contents.includes(POD_MARKER)) return cfg;
      // Insert INSIDE the app target — a pod declared at file scope is not
      // linked into the app and the dependency stays unresolved.
      const target = /target '([^']+)' do\n/;
      const m = contents.match(target);
      if (!m) {
        throw new Error('withJoryioSdk: no target block found in ios/Podfile');
      }
      contents = contents.replace(m[0], m[0] + POD_LINE);
      fs.writeFileSync(podfile, contents);
      return cfg;
    },
  ]);
}

const BLOCK = `
${MARKER} — vendored native SDK (not on Maven; see vendor/joryio)
include ':joryio-sdk'
project(':joryio-sdk').projectDir = new File(rootProject.projectDir, '../vendor/joryio/android/joryio')
include ':joryio-sdk-ui'
project(':joryio-sdk-ui').projectDir = new File(rootProject.projectDir, '../vendor/joryio/android/joryio-ui')
`;

module.exports = function withJoryioSdk(config) {
  const withGradle = withSettingsGradle(config, (cfg) => {
    if (cfg.modResults.contents.includes(MARKER)) return cfg;
    cfg.modResults.contents += BLOCK;
    return cfg;
  });
  return withJoryioPod(withGradle);
};
