// withWearApp — Expo config plugin that adds the Wear OS companion app to
// the generated Android project on every `expo prebuild`.
//
// Because `android/` is gitignored (regenerated by prebuild), the native
// watch code can't just live there. The canonical sources are kept under
// `plugins/wear-src/` (tracked in git); this plugin copies them in and
// wires the Gradle/MainApplication hooks so the watch survives prebuild.
//
// It:
//   1. copies plugins/wear-src/wear  → android/wear            (the module)
//   2. copies plugins/wear-src/watch → android/app/.../watch   (the bridge)
//   3. adds `include ':wear'` to settings.gradle
//   4. adds play-services-wearable to app/build.gradle
//   5. registers WatchBridgePackage in MainApplication
//
// All steps are idempotent.

const {
  withDangerousMod,
  withSettingsGradle,
  withAppBuildGradle,
  withMainApplication,
} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const WEAR_DEP = 'com.google.android.gms:play-services-wearable:18.2.0';
const WATCH_PKG = 'com.studiogameslime.soccerapp.watch.WatchBridgePackage()';

function copyWearSources(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const androidRoot = cfg.modRequest.platformProjectRoot;
      const srcRoot = path.join(__dirname, 'wear-src');

      // 1) Wear module → android/wear
      fs.cpSync(path.join(srcRoot, 'wear'), path.join(androidRoot, 'wear'), {
        recursive: true,
      });

      // 2) Watch bridge → android/app/src/main/java/.../watch
      const watchDest = path.join(
        androidRoot,
        'app/src/main/java/com/studiogameslime/soccerapp/watch',
      );
      fs.mkdirSync(watchDest, { recursive: true });
      const watchSrc = path.join(srcRoot, 'watch');
      for (const file of fs.readdirSync(watchSrc)) {
        fs.copyFileSync(path.join(watchSrc, file), path.join(watchDest, file));
      }

      return cfg;
    },
  ]);
}

function addWearToSettings(config) {
  return withSettingsGradle(config, (cfg) => {
    if (!cfg.modResults.contents.includes("include ':wear'")) {
      cfg.modResults.contents = cfg.modResults.contents.replace(
        "include ':app'",
        "include ':app'\ninclude ':wear'",
      );
    }
    return cfg;
  });
}

function addWearableDep(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (!cfg.modResults.contents.includes('play-services-wearable')) {
      cfg.modResults.contents = cfg.modResults.contents.replace(
        /^dependencies\s*\{/m,
        `dependencies {\n    implementation("${WEAR_DEP}")`,
      );
    }
    return cfg;
  });
}

function registerWatchPackage(config) {
  return withMainApplication(config, (cfg) => {
    if (!cfg.modResults.contents.includes('WatchBridgePackage')) {
      cfg.modResults.contents = cfg.modResults.contents.replace(
        'val packages = PackageList(this).packages',
        `val packages = PackageList(this).packages\n            packages.add(${WATCH_PKG})`,
      );
    }
    return cfg;
  });
}

module.exports = function withWearApp(config) {
  config = copyWearSources(config);
  config = addWearToSettings(config);
  config = addWearableDep(config);
  config = registerWatchPackage(config);
  return config;
};
