// withNotificationColorMerge — settle a manifest-merger conflict that only
// appeared once @react-native-firebase/messaging was added (for the iOS push
// fix; on Android it changes nothing we rely on).
//
// Two libraries declare the SAME meta-data:
//
//   ours, via expo-notifications' `color` option:
//     com.google.firebase.messaging.default_notification_color=@color/notification_icon_color
//   @react-native-firebase/messaging's own manifest:
//     com.google.firebase.messaging.default_notification_color=@color/white
//
// The merger refuses to pick and fails the release build outright:
//
//   Attribute meta-data#...default_notification_color@resource
//   value=(@color/notification_icon_color) ... is also present at
//   [:react-native-firebase_messaging] value=(@color/white)
//
// Its own suggested remedy is tools:replace, which is what this does — ours
// is the deliberate brand colour configured in app.json, theirs is a library
// default of plain white. `android/` is generated by prebuild and gitignored,
// so this cannot be a hand edit to the manifest; it has to be a mod, and it
// has to run after expo-notifications has written the attribute it replaces.
//
// WHICH MEANS IT IS REGISTERED FIRST, not last. Manifest mods compose like
// middleware: the most recently added one is outermost and therefore runs
// EARLIEST. Registered after expo-notifications, this ran before it and found
// no such meta-data; registered dead last, it saw fewer entries still. First
// in the list is last to run, which is the only position where the attribute
// it needs already exists.
const { withAndroidManifest } = require('expo/config-plugins');

const KEY = 'com.google.firebase.messaging.default_notification_color';

function withNotificationColorMerge(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = cfg.modResults.manifest.application?.[0];
    if (!app) return cfg;
    // Declare the tools namespace — a bare prebuild manifest has no reason to
    // carry it, and tools:replace is silently inert without it.
    cfg.modResults.manifest.$['xmlns:tools'] =
      cfg.modResults.manifest.$['xmlns:tools'] ?? 'http://schemas.android.com/tools';
    const meta = (app['meta-data'] ?? []).find(
      (m) => m.$?.['android:name'] === KEY,
    );
    if (meta) meta.$['tools:replace'] = 'android:resource';
    return cfg;
  });
}

module.exports = withNotificationColorMerge;
