#!/usr/bin/env node
// Regenerate the "no-play" Jewish-holiday tables from @hebcal/core (Israel
// scheme). Writes BOTH:
//   • src/utils/holidays.ts        (client, RN bundle)
//   • functions/src/holidays.ts    (backend)
// so they never drift. Run from repo root or functions/:
//   node functions/scripts/genHolidays.mjs [startYear] [endYear]
// Requires @hebcal/core (a functions devDependency):
//   (cd functions && node scripts/genHolidays.mjs 2025 2040)
//
// Two categories:
//   FULL  (CHAG | MAJOR_FAST) — yom-tov + major fasts → warn at ANY time.
//   EREV  (the 5 festival eves) → warn only from mid-afternoon (people still
//         play on a chag-eve MORNING; they stop from ~15:00 when the chag nears).
// @hebcal/core is ESM-only — that's exactly why the app/backend use these STATIC
// tables instead of importing it at runtime.

import { HebrewCalendar, flags } from '@hebcal/core';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const START_YEAR = Number(process.argv[2] || 2025);
const END_YEAR = Number(process.argv[3] || 2035);
const EREV_MIN_HOUR = 15;

const clean = (s) =>
  s
    .normalize('NFC')
    .replace(/[֑-ׇ]/g, '') // nikud
    // Postponed-fast "(נדחה)" renders with unbalanced parens in RTL — drop it.
    .replace(/[()（）]/g, ' ')
    .replace(/\s*נדחה\s*/g, ' ')
    .replace(/\s+\d{3,4}\s*$/, '') // trailing Hebrew year (Rosh Hashana)
    .replace(/\s+/g, ' ')
    .trim();

const keyOf = (ev) => {
  const d = ev.getDate().greg();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
};
const span = { start: new Date(`${START_YEAR}-01-01`), end: new Date(`${END_YEAR}-12-31`), il: true };

// FULL — yom-tov festivals + major fasts.
const fullEvs = HebrewCalendar.calendar({ ...span, mask: flags.CHAG | flags.MAJOR_FAST });
const fullLines = fullEvs.map((ev) => `  '${keyOf(ev)}': '${clean(ev.render('he'))}',`);

// EREV — the festival eves only. hebcal's EREV mask also flags Erev Purim and
// the first Chanukah candle; keep just the "Erev <festival>" days and drop
// Purim + Tish'a B'Av (the latter is already a FULL fast day above).
const erevEvs = HebrewCalendar.calendar({ ...span, mask: flags.EREV }).filter((ev) => {
  const en = ev.render('en');
  return en.startsWith('Erev ') && !/Purim|Tish/.test(en);
});
const erevLines = erevEvs.map((ev) => `  '${keyOf(ev)}': '${clean(ev.render('he'))}',`);

const FULL = fullLines.join('\n');
const EREV = erevLines.join('\n');

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '..', '..');

writeFileSync(resolve(repo, 'src/utils/holidays.ts'), clientFile());
writeFileSync(resolve(repo, 'functions/src/holidays.ts'), backendFile());
console.log(
  `✓ wrote ${fullLines.length} full + ${erevLines.length} erev holidays (${START_YEAR}-${END_YEAR}) → src/utils/holidays.ts + functions/src/holidays.ts`,
);

function clientFile() {
  return `// Jewish "no-play" holidays (Israel scheme) — GENERATED by
// functions/scripts/genHolidays.mjs from @hebcal/core. Do not edit by hand.
// FULL = yom-tov festivals + major fasts (warn at any time). EREV = festival
// eves (warn only from ${EREV_MIN_HOUR}:00 — people still play a chag-eve morning).
// Chanukah/Chol HaMoed/Rosh Chodesh/Purim/modern days are excluded. Static
// offline table so the RN bundle carries no calendar dep. Covers ${START_YEAR}-${END_YEAR}.

export const HOLIDAY_TABLE_MAX_YEAR = ${END_YEAR};
const EREV_MIN_HOUR = ${EREV_MIN_HOUR};

// Full no-play days — warn regardless of kickoff time.
const NO_PLAY_HOLIDAYS: Record<string, string> = {
${FULL}
};

// Festival eves — warn only when kickoff is mid-afternoon or later.
const EREV_HOLIDAYS: Record<string, string> = {
${EREV}
};

/** Local-time 'YYYY-MM-DD' key for a Date (device TZ = Israel for our users). */
function toDateKey(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return \`\${y}-\${m}-\${day}\`;
}

/**
 * Hebrew name of the no-play holiday for the given kickoff, or null. Full days
 * match at any time; festival eves match only from EREV_MIN_HOUR. Beyond the
 * table horizon we fail OPEN (no false warning; the backend still catches it).
 * Accepts epoch-ms or Date.
 */
export function holidayOnDate(input: number | Date): string | null {
  const d = typeof input === 'number' ? new Date(input) : input;
  if (Number.isNaN(d.getTime())) return null;
  const key = toDateKey(d);
  const full = NO_PLAY_HOLIDAYS[key];
  if (full) return full;
  const erev = EREV_HOLIDAYS[key];
  if (erev && d.getHours() >= EREV_MIN_HOUR) return erev;
  return null;
}
`;
}

function backendFile() {
  return `// Backend copy of the "no-play" holidays table — GENERATED by
// functions/scripts/genHolidays.mjs. Mirrors src/utils/holidays.ts. Static (not a
// runtime @hebcal/core import, which is ESM-only and can't be require()'d here).
// FULL = any time; EREV = festival eves, only from ${EREV_MIN_HOUR}:00.

export const HOLIDAY_TABLE_MAX_YEAR = ${END_YEAR};
const EREV_MIN_HOUR = ${EREV_MIN_HOUR};

const NO_PLAY_HOLIDAYS: Record<string, string> = {
${FULL}
};

const EREV_HOLIDAYS: Record<string, string> = {
${EREV}
};

/**
 * Hebrew name of the no-play holiday for the given kickoff, or null. The
 * functions container runs in UTC, so we resolve BOTH the calendar date and the
 * hour via Asia/Jerusalem. Full days match any time; festival eves only from
 * EREV_MIN_HOUR.
 */
export function holidayNameOnDate(startsAt: number): string | null {
  if (!Number.isFinite(startsAt)) return null;
  const parts = new Intl.DateTimeFormat('en-GB', {
    timeZone: 'Asia/Jerusalem',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    hourCycle: 'h23',
  }).formatToParts(new Date(startsAt));
  const get = (t: string) => parts.find((p) => p.type === t)?.value ?? '';
  const key = \`\${get('year')}-\${get('month')}-\${get('day')}\`;
  const hour = Number(get('hour'));
  const full = NO_PLAY_HOLIDAYS[key];
  if (full) return full;
  const erev = EREV_HOLIDAYS[key];
  if (erev && hour >= EREV_MIN_HOUR) return erev;
  return null;
}
`;
}
